### ISSUE TITLE
Chef::Handler::S3 raised #<NoMethodError: undefined method `cloud'

### ISSUE THREAD

**Issue by siddhu07** [juanje/chef-handler-s3#1]
### Chef-client version
In Work Station - 12.21.2
In client - 13.6.4

### Platform Details
client - ubuntu

### Scenario
trying to upload a report file to S3. 

### Steps to Reproduce:
create a cookbook and add the recipe below
[https://github.com/juanje/chef-handler-s3]

### Expected Result:
file should be upload to S3

### Actual Result:
Running handlers:
[2017-12-20T05:35:47+00:00] ERROR: Report handler Chef::Handler::S3 raised #<NoMethodError: undefined method `cloud' for #<Chef::Node::Attribute:0x0000000003bae160>>
[2017-12-20T05:35:47+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/node.rb:267:in `public_send'
[2017-12-20T05:35:47+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/node.rb:267:in `method_missing'
[2017-12-20T05:35:47+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-handler-s3-0.1.2/lib/chef/handler/s3.rb:65:in `report'
[2017-12-20T05:35:47+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/handler.rb:259:in `run_report_unsafe'
[2017-12-20T05:35:47+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/handler.rb:247:in `run_report_safely'
[2017-12-20T05:35:47+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/handler.rb:125:in `block in run_report_handlers'
[2017-12-20T05:35:47+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/handler.rb:123:in `each'
[2017-12-20T05:35:47+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/handler.rb:123:in `run_report_handlers'
[2017-12-20T05:35:47+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/handler.rb:135:in `block in <class:Handler>'
[2017-12-20T05:35:47+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/client.rb:443:in `block in run_completed_successfully'
[2017-12-20T05:35:47+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/client.rb:442:in `each'
[2017-12-20T05:35:47+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/client.rb:442:in `run_completed_successfully'
[2017-12-20T05:35:47+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/client.rb:301:in `run'
[2017-12-20T05:35:47+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/application.rb:291:in `block in fork_chef_client'
[2017-12-20T05:35:47+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/application.rb:279:in `fork'
[2017-12-20T05:35:47+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/application.rb:279:in `fork_chef_client'
[2017-12-20T05:35:47+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/application.rb:244:in `block in run_chef_client'
[2017-12-20T05:35:47+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/local_mode.rb:44:in `with_server_connectivity'
[2017-12-20T05:35:47+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/application.rb:232:in `run_chef_client'
[2017-12-20T05:35:47+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/application/client.rb:469:in `sleep_then_run_chef_client'
[2017-12-20T05:35:47+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/application/client.rb:458:in `block in interval_run_chef_client'
[2017-12-20T05:35:47+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/application/client.rb:457:in `loop'
[2017-12-20T05:35:47+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/application/client.rb:457:in `interval_run_chef_client'
[2017-12-20T05:35:47+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/application/client.rb:441:in `run_application'
[2017-12-20T05:35:47+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/application.rb:59:in `run'
[2017-12-20T05:35:47+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/bin/chef-client:26:in `<top (required)>'
[2017-12-20T05:35:47+00:00] ERROR: /usr/bin/chef-client:58:in `load'
[2017-12-20T05:35:47+00:00] ERROR: /usr/bin/chef-client:58:in `<main>'
  - Chef::Handler::S3
Running handlers complete
Chef Client finished, 0/16 resources updated in 02 seconds

**Comment by lavanyaruth** [comment]
I have got the same issue by running s3 report handler. Did you find the solution for this?
